// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKVaK8srajx2PKU1QSmW2igMLySz5rMVI',
    appId: '1:34496743352:web:pos-podda',
    messagingSenderId: '34496743352',
    projectId: 'pos-podda',
    authDomain: 'pos-podda.firebaseapp.com',
    storageBucket: 'pos-podda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVaK8srajx2PKU1QSmW2igMLySz5rMVI',
    appId: '1:34496743352:android:891c5b55897b6359c8b14d',
    messagingSenderId: '34496743352',
    projectId: 'pos-podda',
    storageBucket: 'pos-podda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Nx3LsFdtbs6mrdVLXdq8ie_mUGgCihM',
    appId: '1:34496743352:ios:7ba03e0922826bddc8b14d',
    messagingSenderId: '34496743352',
    projectId: 'pos-podda',
    storageBucket: 'pos-podda.firebasestorage.app',
    iosBundleId: 'com.smebuddy.smeBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Nx3LsFdtbs6mrdVLXdq8ie_mUGgCihM',
    appId: '1:34496743352:ios:7ba03e0922826bddc8b14d',
    messagingSenderId: '34496743352',
    projectId: 'pos-podda',
    storageBucket: 'pos-podda.firebasestorage.app',
    iosBundleId: 'com.smebuddy.smeBuddy',
  );
}
